apiVersion: "garden.io/v1"
kind: Project
name: terraform-lambda-example
defaultEnvironment: dev
dotIgnoreFile: .gitignore

# Replace this with your project ID and Garden Cloud/Enterprise domain
# You need do this AFTER you import your project in Garden Cloud/Enterprise
# id: <garden-project-id>
# domain: <https://my-garden-app.app.garden>

variables:
  # Replace this with your own backen config. In this project we assume the S3 bucket already exists.
  backendConfig:
    bucket: ${local.env.AWS_S3_BUCKET || "<my-terraform-state-bucket>"}
    region: ${local.env.AWS_REGION || "<my-aws-region>"}

environments:
  - name: dev
    variables:
      namespaceName: dev-${kebabCase(local.username)}
      helloFnName: ${var.namespaceName}-hello-fn
      goodbyeFnName: ${var.namespaceName}-goodbye-fn
      e2eTestRunnerName: ${var.namespaceName}-e2e-test-runner
  - name: ci
    variables:
      namespaceName: ci-${slice(git.commitHash, 0, 7) || '<detached>'}
      helloFnName: ${var.namespaceName}-hello-fn
      goodbyeFnName: ${var.namespaceName}-goodbye-fn
      e2eTestRunnerName: ${var.namespaceName}-e2e-test-runner
  - name: preview
    variables:
      namespaceName: preview-${git.branch}
      helloFnName: ${var.namespaceName}-hello-fn
      goodbyeFnName: ${var.namespaceName}-goodbye-fn
      e2eTestRunnerName: ${var.namespaceName}-e2e-test-runner

providers:
  - name: terraform
    streamLogsToCloud: true
